package com.sms.Frame;

import com.sms.FileIO.FileManager;
import com.sms.FileIO.Sort;
import com.sms.Physical.Customer;
import com.sms.Physical.Entity;
import com.sms.Physical.Order;
import com.sms.Physical.Product;
import com.sms.Panel.CustomerPanelManager;
import com.sms.Panel.OrderPanelManager;
import com.sms.Panel.ProductionPanelManager;
import java.awt.BorderLayout;
import java.awt.Dimension;
import java.awt.GridLayout;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

public class MainGUI extends javax.swing.JFrame {

    private Entity entity;
    
    private JPanel lastPanel;
    public MainGUI() {
        
        initComponents();
        
        entity = new Entity();
        entity.customers = new ArrayList<Customer>();
        entity.orders = new ArrayList<Order>();
        entity.products = new ArrayList<Product>();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu3 = new javax.swing.JMenu();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        mnFile = new javax.swing.JMenu();
        btnOpenFile = new javax.swing.JMenuItem();
        btnSave = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        btnExit = new javax.swing.JMenuItem();
        mnManagement = new javax.swing.JMenu();
        mnitProduct = new javax.swing.JMenuItem();
        mnitCustomer = new javax.swing.JMenuItem();
        mnitOrder = new javax.swing.JMenuItem();

        jMenu1.setText("File");
        jMenuBar2.add(jMenu1);

        jMenu3.setText("Edit");
        jMenuBar2.add(jMenu3);

        jMenu4.setText("File");
        jMenuBar3.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar3.add(jMenu5);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sales Management Systemes");
        setResizable(false);

        mnFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/advanced.png"))); // NOI18N
        mnFile.setText("File");

        btnOpenFile.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        btnOpenFile.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/folder.png"))); // NOI18N
        btnOpenFile.setText("Open File");
        btnOpenFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOpenFileActionPerformed(evt);
            }
        });
        mnFile.add(btnOpenFile);

        btnSave.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/s_add.png"))); // NOI18N
        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        mnFile.add(btnSave);
        mnFile.add(jSeparator1);

        btnExit.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Q, java.awt.event.InputEvent.ALT_MASK));
        btnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/s_close.png"))); // NOI18N
        btnExit.setText("Exit");
        btnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExitActionPerformed(evt);
            }
        });
        mnFile.add(btnExit);

        jMenuBar1.add(mnFile);

        mnManagement.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/applications.png"))); // NOI18N
        mnManagement.setText("Manager");

        mnitProduct.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        mnitProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/Computer On_1.png"))); // NOI18N
        mnitProduct.setText("Production");
        mnitProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitProductActionPerformed(evt);
            }
        });
        mnManagement.add(mnitProduct);

        mnitCustomer.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnitCustomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/users_1.png"))); // NOI18N
        mnitCustomer.setText("Customer");
        mnitCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitCustomerActionPerformed(evt);
            }
        });
        mnManagement.add(mnitCustomer);

        mnitOrder.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        mnitOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/order.png"))); // NOI18N
        mnitOrder.setText("Order");
        mnitOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnitOrderActionPerformed(evt);
            }
        });
        mnManagement.add(mnitOrder);

        jMenuBar1.add(mnManagement);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 535, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 283, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
       //Event Save File
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.home")));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
           try {
               FileManager.SaveData(fileToSave.getAbsolutePath(), entity);
           } catch (IOException ex) {
               Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
            JOptionPane.showMessageDialog(this,"Save Data Success");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void mnitProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitProductActionPerformed
        addNewPanel(new ProductionPanelManager(entity));
    }//GEN-LAST:event_mnitProductActionPerformed

    private void mnitCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitCustomerActionPerformed
         addNewPanel(new CustomerPanelManager(entity));
    }//GEN-LAST:event_mnitCustomerActionPerformed

    private void mnitOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnitOrderActionPerformed
        
        if(entity.customers.size() == 0 || entity.products.size() == 0){
            JOptionPane.showMessageDialog(this,"Product Or Customer Not Exist");
            return;
        }
        addNewPanel(new OrderPanelManager(entity));
    }//GEN-LAST:event_mnitOrderActionPerformed
//Thoát Chương Trình
    private void btnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExitActionPerformed
        System.exit(0);
    }//GEN-LAST:event_btnExitActionPerformed

    private void btnOpenFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOpenFileActionPerformed
        //Event Open File
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();

            try {
                entity = FileManager.LoadData(selectedFile.getAbsolutePath());
            } catch (FileNotFoundException ex) {
                Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
            }

            if(entity.customers == null)
            {
                entity.customers = new ArrayList<Customer>();
            }else{
                Sort.shuffleArray(entity.customers);
            }

            if(entity.orders == null){
                entity.orders = new ArrayList<Order>();
            }else{
                Sort.shuffleArray(entity.orders);
            }

            if(entity.products == null){
                entity.products = new ArrayList<Product>();

            }else{
                Sort.shuffleArray(entity.products);
            }

            JOptionPane.showMessageDialog(this,"Load Data Success");
        }
    }//GEN-LAST:event_btnOpenFileActionPerformed

    private void addNewPanel(JPanel panelManager){

        if(lastPanel != null){
            remove(lastPanel);
        }
        
        setLayout(new BorderLayout());
        add(panelManager);
        pack();
        
        lastPanel = panelManager;
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainGUI().setVisible(true);
            }
            
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem btnExit;
    private javax.swing.JMenuItem btnOpenFile;
    private javax.swing.JMenuItem btnSave;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenu mnFile;
    private javax.swing.JMenu mnManagement;
    private javax.swing.JMenuItem mnitCustomer;
    private javax.swing.JMenuItem mnitOrder;
    private javax.swing.JMenuItem mnitProduct;
    // End of variables declaration//GEN-END:variables
}
