package com.sms.Frame;

import com.sms.FileIO.Sort;
import com.sms.EditType.EditType;
import com.sms.Physical.Customer;
import com.sms.Physical.Order;
import com.sms.Physical.Product;
import com.sms.Panel.OrderPanelManager;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;

public class OrderAdd extends javax.swing.JFrame {

    private EditType editType;
    private Order order;
    OrderPanelManager orderPanelManager;
    
    public OrderAdd(OrderPanelManager orderPanelManager) {
        initComponents();
        
        editType = EditType.CREATE;
        this.orderPanelManager = orderPanelManager;
        
        initData();
    }

    public OrderAdd(OrderPanelManager orderingPanelManager, Order order) {
        initComponents();
        
        
        editType = EditType.EDIT;
        this.order = order;

        this.orderPanelManager = orderingPanelManager;
        
        initData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbQuantity = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btEdit = new javax.swing.JButton();
        lbCustomer = new javax.swing.JLabel();
        lbProduct = new javax.swing.JLabel();
        cbProduct = new javax.swing.JComboBox<>();
        cbCustomer = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Order Edit");
        setAlwaysOnTop(true);
        setResizable(false);

        lbQuantity.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbQuantity.setText("Quantity");

        jLabel1.setText("Add New Order");

        btEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/s_ok.png"))); // NOI18N
        btEdit.setText("Save");
        btEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditActionPerformed(evt);
            }
        });

        lbCustomer.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbCustomer.setText("Customer");

        lbProduct.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbProduct.setText("Product");

        cbProduct.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbProductActionPerformed(evt);
            }
        });

        cbCustomer.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbQuantity, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lbCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
                    .addComponent(lbProduct, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btEdit)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cbCustomer, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(41, Short.MAX_VALUE))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(102, 102, 102))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbProduct, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbProduct))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCustomer)
                    .addComponent(cbCustomer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtQuantity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbQuantity))
                .addGap(18, 18, 18)
                .addComponent(btEdit)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleDescription("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditActionPerformed
        
        order.pcode = orderPanelManager.ett.products.get(cbProduct.getSelectedIndex()).pcode;
        order.ccode = orderPanelManager.ett.customers.get(cbCustomer.getSelectedIndex()).ccode;
        order.quantity = Integer.parseInt(txtQuantity.getText());
        
        if(editType == EditType.CREATE){
            orderPanelManager.ett.orders.add(order);
        }
        this.dispose();
        orderPanelManager.loadDataTab();
    }//GEN-LAST:event_btEditActionPerformed

    private void cbProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbProductActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbProductActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btEdit;
    private javax.swing.JComboBox<String> cbCustomer;
    private javax.swing.JComboBox<String> cbProduct;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lbCustomer;
    private javax.swing.JLabel lbProduct;
    private javax.swing.JLabel lbQuantity;
    private javax.swing.JTextField txtQuantity;
    // End of variables declaration//GEN-END:variables

    private void initData() {
        
        String[] arrProductName = new String[orderPanelManager.ett.products.size()];
        for (int i = 0; i < orderPanelManager.ett.products.size(); i++) {
            arrProductName[i] = orderPanelManager.ett.products.get(i).pro_name;
        }
        cbProduct.setModel(new DefaultComboBoxModel<String>(arrProductName));
       
        String[] arrCustomerName = new String[orderPanelManager.ett.customers.size()];
        for (int i = 0; i < orderPanelManager.ett.customers.size(); i++) {
            arrCustomerName[i] = orderPanelManager.ett.customers.get(i).cus_name;
        }
        cbCustomer.setModel(new DefaultComboBoxModel<String>(arrCustomerName));    
        
        
         if(editType == EditType.CREATE){
            order = new Order();
            
            if((orderPanelManager.ett.products.size()) > 0)
                cbProduct.setSelectedIndex(0);
            
            if((orderPanelManager.ett.customers.size()) > 0)
                cbCustomer.setSelectedIndex(0);
            
        }else{
             
             cbProduct.setSelectedIndex(Sort.getIndexProductByCode(orderPanelManager.ett.products, order.pcode));
             cbCustomer.setSelectedIndex(Sort.getIndexCustomerByCode(orderPanelManager.ett.customers, order.ccode));
             
         }
        

        txtQuantity.setText(""+order.quantity);
    }
}
