package com.sms.Panel;

import com.sms.FileIO.Sort;
import com.sms.Frame.CustomerEdit;
import com.sms.Physical.Customer;
import com.sms.Physical.Entity;
import com.sms.Physical.Product;
import java.awt.Rectangle;
import javax.swing.JOptionPane;

public class CustomerPanelManager extends javax.swing.JPanel {

    public Entity ett;
    
    private String[] columns =  new String [] {
                "Code", "Name", "Phone"
            };
    
    public CustomerPanelManager(Entity entities) {
        initComponents();
        this.ett = entities;
        loadDataTab();
    }
    //This function get Data to Table
    public void loadDataTab() {
        
        if(ett.customers.size() == 0)
            return;
        
        Object[][] arrData = new Object[ett.customers.size()][columns.length];
        
        for(int i = 0 ;i < ett.customers.size();i++){
            Customer product = ett.customers.get(i);
            arrData[i][0] = product.ccode;
            arrData[i][1] = product.cus_name;
            arrData[i][2] = product.phone;
        }
        
         tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            arrData,
           columns
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtSreachByCcode = new javax.swing.JTextField();
        btnSearch_By_CCode = new javax.swing.JButton();
        btnRemove_By_Ccode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCustomer = new javax.swing.JTable();
        btnSort = new javax.swing.JButton();

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/s_add.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/edit.png"))); // NOI18N
        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSreachByCcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSreachByCcodeActionPerformed(evt);
            }
        });

        btnSearch_By_CCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/s_search.png"))); // NOI18N
        btnSearch_By_CCode.setText("Search Customer");
        btnSearch_By_CCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_By_CCodeActionPerformed(evt);
            }
        });

        btnRemove_By_Ccode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/erase.png"))); // NOI18N
        btnRemove_By_Ccode.setText("Delete Customer");
        btnRemove_By_Ccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove_By_CcodeActionPerformed(evt);
            }
        });

        tblCustomer.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Name", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblCustomer.setEditingRow(1);
        tblCustomer.setName(""); // NOI18N
        jScrollPane1.setViewportView(tblCustomer);
        if (tblCustomer.getColumnModel().getColumnCount() > 0) {
            tblCustomer.getColumnModel().getColumn(0).setResizable(false);
            tblCustomer.getColumnModel().getColumn(1).setResizable(false);
            tblCustomer.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSort.setIcon(new javax.swing.ImageIcon(getClass().getResource("/data/icon/down_alt.png"))); // NOI18N
        btnSort.setText("Sort List Customer");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearch_By_CCode, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, Short.MAX_VALUE)
                        .addComponent(btnRemove_By_Ccode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSort)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd)
                    .addComponent(btnSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch_By_CCode)
                    .addComponent(btnRemove_By_Ccode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleParent(jScrollPane1);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Add new Customer
        CustomerEdit editor = new CustomerEdit(this);
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSreachByCcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSreachByCcodeActionPerformed

    }//GEN-LAST:event_txtSreachByCcodeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        //Edit Details Customer
        int index = tblCustomer.getSelectedRow();        
        CustomerEdit editor = new CustomerEdit(this, ett.customers.get(index));
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        //Sort List Customer
        Sort.quicksort(ett.customers);
        loadDataTab();
        JOptionPane.showMessageDialog(this,"Sorted Success");
    }//GEN-LAST:event_btnSortActionPerformed

    
    
    private void btnSearch_By_CCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_By_CCodeActionPerformed
        //Search Customer by ccode
        Sort.quicksort(ett.customers);
        loadDataTab();
        String code = txtSreachByCcode.getText();
        int result = Sort.binarysreach(ett.customers, new Customer(code));
        if(result != -1)
        {
             tblCustomer.getSelectionModel().setSelectionInterval(result, result);
             tblCustomer.scrollRectToVisible(new Rectangle(tblCustomer.getCellRect(result, 0, true)));
            JOptionPane.showMessageDialog(this,"Customer Found");
        }else
        {
            JOptionPane.showMessageDialog(this,"Customer Not Exist");
        }
    }//GEN-LAST:event_btnSearch_By_CCodeActionPerformed

    private void btnRemove_By_CcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove_By_CcodeActionPerformed
        //Remove Customer by ccode
        Sort.quicksort(ett.customers);
        loadDataTab();
        String code = txtSreachByCcode.getText();
        int result = Sort.binarysreach(ett.customers, new Customer(code));
        if(result != -1)
        {
            ett.customers.remove(result);
            JOptionPane.showMessageDialog(this,"Removed Success");
        }else
        {
            JOptionPane.showMessageDialog(this,"Customer Not Exist");
        }
    }//GEN-LAST:event_btnRemove_By_CcodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove_By_Ccode;
    private javax.swing.JButton btnSearch_By_CCode;
    private javax.swing.JButton btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblCustomer;
    private javax.swing.JTextField txtSreachByCcode;
    // End of variables declaration//GEN-END:variables

   
}
