package com.sms.Panel;

import com.sms.FileIO.Helper;
import com.sms.Frame.CustomerEdit;
import com.sms.Physical.Customer;
import com.sms.Physical.Entity;
import com.sms.Physical.Product;
import javax.swing.JOptionPane;

public class CustomerPanelManager extends javax.swing.JPanel {

    public Entity entities;
    
    private String[] columns =  new String [] {
                "Code", "Name", "Phone"
            };
    
    public CustomerPanelManager(Entity entities) {
        initComponents();
        this.entities = entities;
        loadDataTab();
    }
    
    public void loadDataTab() {
        
        if(entities.customers.size() == 0)
            return;
        
        Object[][] arrData = new Object[entities.customers.size()][columns.length];
        
        for(int i = 0 ;i < entities.customers.size();i++){
            Customer product = entities.customers.get(i);
            arrData[i][0] = product.ccode;
            arrData[i][1] = product.cus_name;
            arrData[i][2] = product.phone;
        }
        
         jTable1.setModel(new javax.swing.table.DefaultTableModel(
            arrData,
           columns
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        txtSreachByCcode = new javax.swing.JTextField();
        btnSearch_By_CCode = new javax.swing.JButton();
        btnRemove_By_Ccode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        btnSort = new javax.swing.JButton();

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        txtSreachByCcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSreachByCcodeActionPerformed(evt);
            }
        });

        btnSearch_By_CCode.setText("Search Customer");
        btnSearch_By_CCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearch_By_CCodeActionPerformed(evt);
            }
        });

        btnRemove_By_Ccode.setText("Delete Customer");
        btnRemove_By_Ccode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemove_By_CcodeActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Code", "Name", "Phone"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
        }

        btnSort.setText("Sort List Customer");
        btnSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnEdit)
                        .addGap(176, 176, 176)
                        .addComponent(btnSort, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSearch_By_CCode)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnRemove_By_Ccode)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnEdit)
                    .addComponent(btnAdd)
                    .addComponent(btnSort))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch_By_CCode)
                    .addComponent(btnRemove_By_Ccode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        CustomerEdit editor = new CustomerEdit(this);
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSreachByCcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSreachByCcodeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSreachByCcodeActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:
        int index = jTable1.getSelectedRow();
        CustomerEdit editor = new CustomerEdit(this, entities.customers.get(index));
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btnEditActionPerformed

    private void btnSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortActionPerformed
        Helper.quicksort(entities.products);
        loadDataTab();
        JOptionPane.showMessageDialog(this,"Sorted Success");
    }//GEN-LAST:event_btnSortActionPerformed

    private void btnSearch_By_CCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearch_By_CCodeActionPerformed
        // TODO add your handling code here:
        
        String code = txtSreachByCcode.getText();
        int result = Helper.binarysreach(entities.customers, new Customer(code));
        if(result != -1){
             jTable1.getSelectionModel().setSelectionInterval(0, result);
            JOptionPane.showMessageDialog(this,"Found");
        }else{
            JOptionPane.showMessageDialog(this,"Customer Not Found");
        }
    }//GEN-LAST:event_btnSearch_By_CCodeActionPerformed

    private void btnRemove_By_CcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemove_By_CcodeActionPerformed
       String code = txtSreachByCcode.getText();
        int result = Helper.binarysreach(entities.customers, new Customer(code));
        if(result != -1){
            entities.customers.remove(result);
            JOptionPane.showMessageDialog(this,"Remove Success");
        }else{
            JOptionPane.showMessageDialog(this,"Customer Not Exist");
        }
    }//GEN-LAST:event_btnRemove_By_CcodeActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnRemove_By_Ccode;
    private javax.swing.JButton btnSearch_By_CCode;
    private javax.swing.JButton btnSort;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField txtSreachByCcode;
    // End of variables declaration//GEN-END:variables

   
}
