package com.sms.Panel;

import com.sms.EditType.EditType;
import com.sms.FileIO.FileManager;
import com.sms.FileIO.Sort;
import com.sms.Frame.MainGUI;
import com.sms.Frame.ProductAdd;
import com.sms.Physical.Entity;
import com.sms.Physical.Order;
import com.sms.Physical.Product;
import java.awt.Rectangle;
import java.io.File;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

public class ProductPanelManager extends javax.swing.JPanel {

    public Entity ett;
    private EditType editType;
    private Product product;
    
    private String[] columns = new String [] 
    {
        "Code",
        "Name", 
        "Quantity", 
        "Saled", 
        "Price"
    };

    public ProductPanelManager(Entity entity) 
    {
        initComponents();
        this.ett = entity;
        loadDataTab();
    }
    
    public void loadDataTab()
    {
        
        if(ett.products.size() == 0)
            return;
        
        Object[][] arrData = new Object[ett.products.size()][columns.length];
        
        for(int i = 0 ;i < ett.products.size();i++){
            Product product = ett.products.get(i);
            arrData[i][0] = product.pcode;
            arrData[i][1] = product.pro_name;
            arrData[i][2] = product.quantity;
            arrData[i][3] = product.saled;
            arrData[i][4] = product.price;
        }
        
        tblProduct.setModel(new DefaultTableModel(arrData,columns) 
        {
            Class[] types = new Class [] 
            {
                java.lang.String.class,
                java.lang.String.class,
                java.lang.Integer.class,
                java.lang.Integer.class,
                java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] 
            {
                true,
                true,
                true,
                true,
                true
            };

            @Override
            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) 
            {
                return canEdit [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnAdd = new javax.swing.JButton();
        btnSearchBy_Pcode = new javax.swing.JButton();
        btnRemoveByPCode = new javax.swing.JButton();
        txtSreachByCcode = new javax.swing.JTextField();
        btnSortby_PCode = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblProduct = new javax.swing.JTable();
        btnLoadData = new javax.swing.JButton();
        btnSave = new javax.swing.JButton();

        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                formFocusLost(evt);
            }
        });

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/s_add.png"))); // NOI18N
        btnAdd.setText("Add Product");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnSearchBy_Pcode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/s_search.png"))); // NOI18N
        btnSearchBy_Pcode.setText("Sreach Product");
        btnSearchBy_Pcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchBy_PcodeActionPerformed(evt);
            }
        });

        btnRemoveByPCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/erase.png"))); // NOI18N
        btnRemoveByPCode.setText("Delete Product");
        btnRemoveByPCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveByPCodeActionPerformed(evt);
            }
        });

        txtSreachByCcode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSreachByCcodeActionPerformed(evt);
            }
        });

        btnSortby_PCode.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/down_alt.png"))); // NOI18N
        btnSortby_PCode.setText("Sort List Product");
        btnSortby_PCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSortby_PCodeActionPerformed(evt);
            }
        });

        tblProduct.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Code", "Name", "Quantity", "Saled", "Price"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Float.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblProduct.setEditingRow(1);
        tblProduct.setSelectionBackground(new java.awt.Color(153, 102, 255));
        tblProduct.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(tblProduct);
        if (tblProduct.getColumnModel().getColumnCount() > 0) {
            tblProduct.getColumnModel().getColumn(0).setResizable(false);
            tblProduct.getColumnModel().getColumn(1).setResizable(false);
            tblProduct.getColumnModel().getColumn(2).setResizable(false);
            tblProduct.getColumnModel().getColumn(3).setResizable(false);
            tblProduct.getColumnModel().getColumn(4).setResizable(false);
        }

        btnLoadData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/folder.png"))); // NOI18N
        btnLoadData.setText("Load Data");
        btnLoadData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoadDataActionPerformed(evt);
            }
        });

        btnSave.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/sms/icon/s_product.png"))); // NOI18N
        btnSave.setText("Save Data");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnLoadData, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSortby_PCode, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnSearchBy_Pcode, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRemoveByPCode, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnSortby_PCode)
                    .addComponent(btnLoadData)
                    .addComponent(btnSave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSreachByCcode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchBy_Pcode)
                    .addComponent(btnRemoveByPCode))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        //Thêm mới 1 product
        ProductAdd editor = new ProductAdd(this);
        editor.setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        editor.setVisible(true);
    }//GEN-LAST:event_btnAddActionPerformed

    private void txtSreachByCcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSreachByCcodeActionPerformed

    }//GEN-LAST:event_txtSreachByCcodeActionPerformed

    private void formFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusLost

    }//GEN-LAST:event_formFocusLost

    private void btnSortby_PCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSortby_PCodeActionPerformed
        //Sort Product By pcode a->z
        Sort.quicksort(ett.products);
        loadDataTab();
        JOptionPane.showMessageDialog(this,"Sorted Product");
    }//GEN-LAST:event_btnSortby_PCodeActionPerformed

    private void btnSearchBy_PcodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchBy_PcodeActionPerformed
        //Search Product By pcode
        Sort.quicksort(ett.products);
        loadDataTab();
        String code = txtSreachByCcode.getText();
        int result = Sort.binarySearch(ett.products, new Product(code));
         if(result != -1){
            tblProduct.getSelectionModel().setSelectionInterval(result, result);
            tblProduct.scrollRectToVisible(new Rectangle(tblProduct.getCellRect(result, 0, true)));
            JOptionPane.showMessageDialog(this,"Product Found");
        }else{
            JOptionPane.showMessageDialog(this,"Product Not Found");
        }
    }//GEN-LAST:event_btnSearchBy_PcodeActionPerformed

    private void btnRemoveByPCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveByPCodeActionPerformed
        //Remove Product By pcode
        Sort.quicksort(ett.products);
        loadDataTab();
        int index = tblProduct.getSelectedRow();
        String code = txtSreachByCcode.getText();
        int result = Sort.binarySearch(ett.products, new Product(code));
        if(result != -1){
            ett.products.remove(result);
            JOptionPane.showMessageDialog(this,"Removed Success");
        }else{
            JOptionPane.showMessageDialog(this,"Product Not Exist");
        }
        loadDataTab();
    }//GEN-LAST:event_btnRemoveByPCodeActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showSaveDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
           try {
               FileManager.SaveData(fileToSave.getAbsolutePath(), ett);
           } catch (IOException ex) {
               Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
            JOptionPane.showMessageDialog(this,"Save Data Product Success");
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnLoadDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoadDataActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File(System.getProperty("user.dir")));
        int result = fileChooser.showOpenDialog(this);
        if (result == JFileChooser.APPROVE_OPTION) {
            File selectedFile = fileChooser.getSelectedFile();
           try {
               ett = FileManager.LoadData(selectedFile.getAbsolutePath());
           } catch (IOException ex) {
               Logger.getLogger(MainGUI.class.getName()).log(Level.SEVERE, null, ex);
           }
           if(ett.products == null)
           {
               ett.products = new ArrayList<Product>();
           }
           loadDataTab();
            JOptionPane.showMessageDialog(this,"Load Data Product Success");
        }
    }//GEN-LAST:event_btnLoadDataActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLoadData;
    private javax.swing.JButton btnRemoveByPCode;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnSearchBy_Pcode;
    private javax.swing.JButton btnSortby_PCode;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblProduct;
    private javax.swing.JTextField txtSreachByCcode;
    // End of variables declaration//GEN-END:variables
}
